### ISSUE TITLE
Unipager - PA Output Level beim Raspager V1

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#103]
Hallo Ralf,

mir ist aufgefallen das in der Unipager-Config der PA Output Level beim Raspager V1 per default auf 30 gesetzt ist.

In der "alten" rasPager.jar-Software war hier eine Einstellung von bis zu 63 (max. Sendeleitung) möglich, ebenso kann man den Wert im
Webinterface des Unipager auf diesen Wert erhöhen.

Die Frage wäre, gibt es einen wichtigen Grund für den Default-Wert von 30? Evtl. Oberwellen oder andere Probleme?
Bei der geringen Sendeleistung des Raspager will man ja nicht noch extra die Reichweite beschränken

Gruß Peter, DG3GSP

**Comment by 7h0ma5** [comment]
Ich werde den Standard auf 63 ändern. Mir ist wohl heute morgen aufgefallen, dass noch ein Bug existierte und immer mit voller Sendeleistung gesendet wurde. Das ist in unipager-testing schon behoben. Eine Verbesserung der Reichweite wird sich deshalb leider nicht ergeben.
