### ISSUE TITLE
Problem: UniPager 0.7.1 Pi2 - Software stürzt bei gedrückter PTT ab.

### ISSUE THREAD

**Issue by DL8KFO** [rwth-afu/UniPager#105]
Folgendes Problem trott auf. Nach längerer Laufzeit (1-2 Tage) scheint UniPager abzustürzen. Dabei verbleibt GPIO0 auf Low und der GM1200 sendet dauerhaft einen stummen Träger. Dennoch bleibt der Pi im Netzwerk erkennbar, kann aber über Port 8073 nicht mehr angesprochen werden. Im DAPNET wird der TX weiter als "Online" angezeigt. Kann jemand das Problem nachvollziehen?

73
  Torsten

**Comment by dh3wr** [comment]
Greift irdendetwas anderes auf GPIO0 zu?

**Comment by dj7lc** [comment]
Genau diesen Fehler hatte ich mit genau dieser Version auch an einigen Sendern beobachten können. In der aktuellen Version tritt das Problem nicht mehr auf. Ich wage zu behaupten, dass wir hier zu machen können.
