### ISSUE TITLE
Setup Raspi testing farm?

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#108]
Sollen wir mal eine Raspi testing farm aufsetzen mit allen Versionen vom Raspi, auf denen man automatisierte Tests laufen lässt? Vielleicht sogar mit RasPagern drauf und einem DVB-T Stick, mit dem wir sogar die POCSAG-Signal mit https://github.com/EliasOenal/multimon-ng dekodieren und verifizieren?

**Comment by 7h0ma5** [comment]
Kann man machen, wenn man genug Geld und Zeit hat. Aber solche Probleme wie eben, wo der Raspberry Pi nicht erkannt wurde, weil er eine neue Revisionsnummer hatte, können damit nicht erkannt werden.

**Comment by dh3wr** [comment]
dann nicht. :-)
