### ISSUE TITLE
Rubriken ab 96 werden auf 32 gemappt

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#113]
Siehe https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/159

**Comment by dh3wr** [comment]
Es mag hier das falsche Mapping geschehen:
https://github.com/rwth-afu/UniPager/blob/master/src/connection.rs
Zeile 211ff. ``fn handle_message(&mut self, data: &str) -> Result<AckStatus> {``

**Comment by 7h0ma5** [comment]
Wenn würde das hier dran liegen: https://github.com/rwth-afu/UniPager/blob/master/src/pocsag/encoding.rs#L8

Alle Bytes größer als 127 werden zu einem 0x3F, also einem "?" gemappt, da es sich um kein gültiges ASCII-Zeichen handelt. Größer geht auch gar nicht, da Alphanumerische Zeichen im POCSAG-Standard nur 7 Bit groß sind.

**Comment by dh3wr** [comment]
Liegt nicht an Unipager, sondern 95 ist die max. Rubrikennummer. Fertig.
