### ISSUE TITLE
Support RasPi 3B+

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#114]
Zur Zeit "unknown RasPi detected" beim Pi3B+. Brauchst du noch weitere Daten?

**Comment by dh3wr** [comment]
![sreenshot-1](https://user-images.githubusercontent.com/16710361/39357047-e82d7fa2-4a11-11e8-8dc5-ff94d99c10b2.png)

**Comment by 7h0ma5** [comment]
Ich bräuchte die Revision aus `/proc/cpuinfo`, laut [elinux.org](https://elinux.org/RPi_HardwareHistory#Board_Revision_History) müsste das `a020d3` sein. Ich gehe mal davon aus, dass die GPIOs gleich geblieben sind?

**Comment by dh3wr** [comment]
Auf der Platine ja, was die RasPi-Zuodnung angeht, so gehe ich auch von Gleichheit aus. cpuinfo kommt.

**Comment by dh3wr** [comment]
pi@raspberrypi:~ $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                                                vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                                                vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                                                vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                                                vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
Hardware        : BCM2835
Revision        : a020d3
Serial          : 0000000072d2d5e9

**Comment by 7h0ma5** [comment]
Gefixt in https://github.com/rwth-afu/UniPager/commit/7b690281d419fb92647c0e5865c4a43703ef7a09. UniPager 1.0.1 müsste gleich im stable-Repository auftauchen.
