### ISSUE TITLE
Username / Passwort für die Settings auf der Website

### ISSUE THREAD

**Issue by rtausend** [rwth-afu/UniPager#12]
Hallo,

ich glaube es wäre sicher sinnvoll noch eine Username/Passwortabfrage für die Einstellungen zu implementieren. Sicher im AFU soll alles offen sein, aber ich denke ein Senderbetreiber möchte nicht das jeder den Sender verstellen kann.

Vielleicht ist dieses Erweiterung auch schon angedacht, wollte es nur mal angesprochen haben.

Gruß Robert

**Comment by daccle** [comment]
@rtausend vielleicht hilft Dir das iptables Beispiel in https://github.com/rwth-afu/RustPager/issues/37 ? Dafür muss natürlich die default policy drop sein. So kann man das Webinterface zumindest nur von lokal aus sehen.

**Comment by rtausend** [comment]
Das ist ne gute idee, aber vielleicht möchte ich die Website ja auch von anderen Rechner erreichen, ich denke ein Passwortschutz ist hier schon wichtig

**Comment by daccle** [comment]
Dafür gibt es ssh-tunnel oder richte halt einen Proxy mit einem Webserver Deiner Wahl ein. (Ich verstehe Deinen Featurewunsch trotzdem ;-) )


Am 24. März 2017 17:10:01 MEZ schrieb rtausend <notifications@github.com>:
>Das ist ne gute idee, aber vielleicht möchte ich die Website ja auch
>von anderen Rechner erreichen, ich denke ein Passwortschutz ist hier
>schon wichtig
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/rwth-afu/UniPager/issues/12#issuecomment-289067413


-- 
Daniel Clerc +49 177 324 65 30

netzguerilla.net GbR • Singerstraße 109 • 10179 Berlin
fon: +49 30 69201075 • mail: kontakt@netzguerilla.net

Gesellschafter: Daniel Clerc, Sandro Knauß, Sebastian Vollnhals
Umsatzsteuer-Identifikationsnummer gemäß §27a UStG: DE271587697

**Comment by dh3wr** [comment]
Ich würde auch sagen: Was wäre die nächste Aktion in der Prio-Liste. Insb. da nun die Testbutton-Fkt. eingebaut ist.

**Comment by dh3wr** [comment]
Hier würde ich auch die Prio etwas hoch setzen :-)

**Comment by 7h0ma5** [comment]
Man kann jetzt ein Passwort setzen, indem man die Datei `/var/lib/unipager/password` anlegt und das Passwort da rein schreibt. Danach muss man den UniPager einmal neustarten. Ich werde bald auch noch eine Option zum Setzen des Passworts in das Webinterface einbauen, das ist aber etwas komplizierter.

**Comment by DL1AFA** [comment]
Muss man bei der Vergabe des Passwortes irgendetwas besonderes beachten? Bei mir funktioniert das nicht oder habe ich das falsch verstanden, dass das Passwort dann für die Webschnittstelle gilt?

**Comment by dh3wr** [comment]
Ja das PW gilt dann für das Web-Interface auf Port 8073 und intern auch für Websocket auf Port 8055. Ziel ist es, dass nicht jeder die Unipager-Einstellungen ändern kann.

**Comment by M6NBP** [comment]
I can not log in via a 2nd PC 
Ports 8073 and 8055 is open 
I have made /var/lib/unipager/password and entered password 

I still can not get pass the password

**Comment by M6NBP** [comment]
Found the issue
It is the Adaware Antivirus Pro
No way to set a rule to over ride.
So for now the only way is to turn it off
