### ISSUE TITLE
RabbitMQ-Version: Manual paging from webpage not working

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#132]
![grafik](https://user-images.githubusercontent.com/16710361/51747152-efb93e00-20a8-11e9-89c4-df3baeac3af5.png)

**Comment by dh3wr** [comment]
Ist immer noch da
![grafik](https://user-images.githubusercontent.com/16710361/53158891-f615d980-35c4-11e9-949f-112eb24682bc.png)

Aber nicht bei allen Klicks auf den Send-Button. System ist noch nicht erkannt, wann es auftaucht

**Comment by 7h0ma5** [comment]
Kann ich bisher nicht reproduzieren.
