### ISSUE TITLE
RabbitMQ-Version: RabbitMQ-Connection Port static?

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#134]
Klarmachen, dass es sich bei dem Port-Textfeld um den http Port handelt. Ggf. den RabbitMQ-Port ebenfalls änderbar machen

**Comment by 7h0ma5** [comment]
Der RabbitMQ-Port eines Cores ist momentan noch nicht änderbar, ein anderer Port sollte dann aber in Zukunft den Clients über den HTTP-Bootstrap-Response mitgeteilt werden.

Siehe https://github.com/dapnet-core/documentation/issues/8
