### ISSUE TITLE
RabbitMQ-Version: Reconnect every minute

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#135]
Sicher schon bekannt und vielleicht falsch in diesem Repo, aber zur Übersicht:
![grafik](https://user-images.githubusercontent.com/16710361/51747339-766e1b00-20a9-11e9-9e8e-fcfc2e3ec06f.png)

**Comment by 7h0ma5** [comment]
Dabei hat es sich um die Heartbeats gehandelt. Die Logausgabe habe ich jetzt geändert, damit das sofort ersichtlich ist.
