### ISSUE TITLE
Standalone mode without server

### ISSUE THREAD

**Issue by robo-w** [rwth-afu/UniPager#148]
Since the UniPager project replaced the SRDPager, it would be nice to have a configuration without any server configured.

Currently there are following limitations:
* There are hardcoded servers in the binaries, if the configuration file is empty.
* There are default servers shipped, which are again in the list if the config is reset on the webui.
* If all servers are removed, and only one invalid host is entered as server (for example "server.invalid"), UniPager constantly tries to reconnect and the CPU is running at almost 100%.

Is there currently an option to run the UniPager standalone, just to send messages via web or command line? If not, it would be a nice improvement.

**Comment by demslob** [comment]
Totally agree
