### ISSUE TITLE
Info über Verbindungsverlust zum Master als Funkruf

### ISSUE THREAD

**Issue by dj7lc** [rwth-afu/UniPager#35]
Wenn der Rustpager die Verbindung zum Master verliert, wäre eine Info an den Senderbetreiber ganz praktisch. Dazu könnte im Webinterface ein Eingabefeld für eine Zieladresse angelegt werden, die nach Ablauf einer Zeitspanne ohne Verbindung oder bei sonstigen Störungen automatisch per Funkruf benachrichtigt wird.

**Comment by dh3wr** [comment]
Das könnte man doch gut über ein Python-Skript erledigen, dass über Websocket angebunden ist, oder?

**Comment by dj7lc** [comment]
Jetzt wo es die lokale Schnittstelle gibt, ist das natürlich kein Problem.
