### ISSUE TITLE
UniPager verliert im Dauerbetrieb die Verbindung

### ISSUE THREAD

**Issue by dj7lc** [rwth-afu/UniPager#61]
Nach längerer Betriebszeit verliert der UniPager die Verbindung zu Dapnet und wird in der Übersicht mit "Error" gelistet. Ein Klick auf "Restart" im Webinterface behebt das Problem. Die Lösung könnte ein Cronjob oder Timer sein, der die "Restart"-Routine jede Nacht einmal ausführt.

**Comment by Taronyu** [comment]
Da würde ich ehrlich gesagt erst einmal etwas Energie in die Diagnose stecken. Kann auch gut sein, dass der Fehler vom Core ausgeht.

**Comment by MurrayBozinsky** [comment]
Hier (DM0AI und DB0PRT je am VDSL-Anschluss der .T...) verlieren die
(bislang noch Rust)Pager die Verbindung immer zur nächtlichen Zwangstrennung.
Ein morgendlicher Restart heilt alles, aber von 3:20 nachts bis zu $Aufstehzeit läuft kein Pagersender.

**Comment by Taronyu** [comment]
Okay, Zwangstrennung hatte ich vergessen, das muss dann tatsächlich der
Client handhaben.

**Comment by 7h0ma5** [comment]
Mit der neusten Version im Debian-Repository sollte nach spätestens 2 Minuten die Verbindung wieder neu hergestellt werden. Bitte mit `sudo apt-get update` und `sudo apt-get upgrade` aktualisieren.

**Comment by MurrayBozinsky** [comment]
Funktioniert bislang, die erste Zwangstrennung heute nacht wurde ohne ERROR überstanden

**Comment by dh3wr** [comment]
Dann kann das zugemacht werden?
