### ISSUE TITLE
Ignoring "unipager" as it has no filename extension

### ISSUE THREAD

**Issue by MurrayBozinsky** [rwth-afu/UniPager#63]
HW: RasPi3, RaspbianJessy

sudo apt-get update
.....
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Reading package lists... Done               
N: Ignoring file 'unipager' in directory '/etc/apt/sources.list.d/' as it has no filename extension
pi@DM0AI-7:~ $

**Comment by 7h0ma5** [comment]
In das README hatte sich ein Fehler eingeschlichen, die Datei in `/etc/apt/sources.list.d/` muss `unipager.list` und nicht `unipager` heißen. Das README ist mit dem neusten Commit aktualisiert.
