### ISSUE TITLE
Sendung geht über Timeslots hinaus oder Anzeige falsch

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#66]
Das sollte man doch eigentlich nicht sehen, oder? Version 0.5.1
![grafik](https://cloud.githubusercontent.com/assets/16710361/24372038/0664ed1a-132d-11e7-8197-90d10bdfc30e.png)

Also noch On-Air, aber schon ein Timeslot weiter

**Comment by dh3wr** [comment]
Geht sogar noch schlimmer
![grafik](https://cloud.githubusercontent.com/assets/16710361/24372108/303239fe-132d-11e7-8de9-e123df9714e4.png)

**Comment by 7h0ma5** [comment]
Das kann daran liegen, dass die TimeSlot-Implementierung noch nicht perfekt ist. Momentan wird nur getestet, ob der Start einer Nachricht noch im TimeSlot drin liegt. Die Berechnung der Übertragungsdauer wird aber komplett neu gemacht. So weit wie im 2. Bild sollte das aber eigentlich nicht gehen, höchstens 100 ms drüber.

**Comment by dh3wr** [comment]
Tja, ist wohl aber so... http://44.225.164.234:8073/ :-)

**Comment by 7h0ma5** [comment]
Interessant, was für ein Skript benutzt du da zum Testen?

**Comment by dh3wr** [comment]
````
#!/usr/bin/python3
import json
import pprint
import websocket
import time
from websocket import create_connection

websocket.enableTrace(True)
ws = create_connection('ws://44.225.164.234:8055/')

n = 1

while n <= 100:
    string_to_send = "{\"SendMessage\": {\"addr\": %s, \"data\": \"%s\"}}" % (n,n)
    print(string_to_send)
    ws.send(string_to_send)
    n = n + 1
    time.sleep( 1 )
````

**Comment by dh3wr** [comment]
Ich mache hier nochmal eine Erinnerung dran, denn das Verhalten ist natürlich nicht so der Knaller.

**Comment by dh3wr** [comment]
Ich bekomme zunehmend Rückmeldungen z.B. aus Schleswig-Holstein, wo sich ein wahres POCSAG-Sender-Paradis aufgebaut hat, dass sich die Sender gegenseitig überlagern. Vielleicht kannst noch nochmal hierrauf den Fokus legen, bitte?

**Comment by 7h0ma5** [comment]
Das Problem betraf nur die Transmitter vom Typ `Audio`. Der Scheduler ist jetzt überarbeitet und das Problem sollte nicht mehr auftreten. Ich habe ein neues Repository mit dem Namen `unipager-testing` eingerichtet, in dem immer die neusten Versionen vom master-Branch landen, so können wir das erstmal auf wenigen Instanzen testen. Man muss dafür einfach in der Datei `/etc/apt/sources.list.d/unipager.list` den Namen des Repositories von `unipager` in `unipager-testing` ändern und dann `apt-get update` und `apt-get upgrade` ausführen.

`unipager.list`:

    deb     http://www.afu.rwth-aachen.de/debian unipager-testing main
    deb-src http://www.afu.rwth-aachen.de/debian unipager-testing main

**Comment by dh3wr** [comment]
Ich habe das Fehlverhalten nicht mehr beobachtet. Kann geschlossen werden und ein neues Stable-Release gemacht werden.
