### ISSUE TITLE
Füllstand der Sender-Queue auf Webseite darstellen

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#67]
Zumindest einmal pro Slot-Aktualisierung könnte man den Füllstand der Sender-Queue ausgeben. Dann kann man sehen, ob die Anzahl an Zeitschlitzen reicht für diesen Sender.

**Comment by dh3wr** [comment]
Kann man das noch über irgendwas munin und nagios kompatibles ausgeben? Oder einfach WS?

**Comment by 7h0ma5** [comment]
Über den WebSocket wäre das am einfachsten, ich habe gerade mal die Dokumentation dazu aktualisiert: https://github.com/rwth-afu/UniPager/wiki/Websocket-Protocol#status

**Comment by dh3wr** [comment]
Dann muss ich wohl https://github.com/rwth-afu/UniPagerNagios/blob/master/src/main.cpp modifizieren
