### ISSUE TITLE
GPIO Fehlermeldung

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#69]
DL2MAI schreibt:
``thread '<unnamed>' panicked at 'Failed to map GPIO', /checkout/src/libcore/option.rs:794``
Was kann der Grund sein?

**Comment by 7h0ma5** [comment]
Vielleicht manuell und nicht als root gestartet. Sonst kann dieses Problem auf einem Raspberry Pi eigentlich nicht auftreten.
