### ISSUE TITLE
Master Verbindung und belegte Que als GPIO Output

### ISSUE THREAD

**Issue by dg8ygz** [rwth-afu/UniPager#70]
Es wäre toll, wenn man wie beim RPC damals man an einer LED sehen kann, ob der Master verbunden ist. Ebenso gabs noch eine Ausgabe, wenn die Que noch nicht leer war. 

Beides wird ja schon auf der Webseite angezeigt, kann man den Status noch auf definierbare GPIOs legen ?

73s de Olaf dg8ygz

**Comment by dh3wr** [comment]
Siehe https://github.com/rwth-afu/UniPagerLED
Die Queue wird noch nicht angegeben. Siehe https://github.com/rwth-afu/UniPager/issues/67
