### ISSUE TITLE
Nach Update auf 0.5.1 geht Unipager nicht mehr

### ISSUE THREAD

**Issue by dj7lc** [rwth-afu/UniPager#73]
Ich habe soeben das Update auf 0.5.1 durchgeführt:
sudo apt update
sudo apt upgrade
Unipager wurde als zu aktualisierendes Paket gelistet und entsprechend aktualisiert.
Unipager wird jetzt nicht mehr automatisch gestartet und lässt sich auch manuell mit
sudo systemctl start unipager.service
oder
sudo systemctl start unipager
nicht mehr starten.
systemctl gibt aus
● unipager.service                             loaded failed failed    UniPager POCSAG transmitter controller
Unter top werden die Unipager-Prozesse ebenfalls nicht gelistet.
Einen SSH-Zugang zum Raspberry kann ich bei Bedarf bereitstellen.

**Comment by 7h0ma5** [comment]
Nachdem ich gestern stundenlang nach der Ursache gesucht habe, sollte es mit der neusten Version wieder gehen. Das Problem war, dass die Standardbibliothek seit neustem für die ARMv7 Architektur kompiliert wird, der Raspberry Pi 1 unterstützt aber nur ARMv6-Instruktionen. Jetzt wird explizit immer die Standardbibliothek für ARMv6 verwendet.

**Comment by dj7lc** [comment]
Der Sender geht wieder! Ich weiß aus eigener Erfahrung, wie es ist nach solchen Fehlern zu suchen. Danke!
