### ISSUE TITLE
Default URL für Master nicht im Package angeben

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#80]
Wir haben immer 2 bis 5 Installationen, bei denen die Leute wohl das Paket installiert haben, aber nie konfiguriert haben. Resultat ist alle 2 Sekunden ein connect request zum Core. Vielleicht kann man die richtige Server-Adresse aus den default-Einstellungen rausnehmen und statt dessen das Feld leer lassen mit einem Hinweis?

**Comment by 7h0ma5** [comment]
Es wird jetzt nur versucht zu verbinden, wenn ein Rufzeichen und ein Auth Key eingegeben wurden.
