### ISSUE TITLE
Messages in queue are reduces by 1 each time save config is pressed

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#89]
Wenn man Nachrichten in der Queue hat und es aber gerade kein aktiver Zeitschlitz ist und man dann Save Config oder restart drückt, wird die Anzahl der angezeigten Queue um 1 verrringert. Dies auch mehrfach bei mehrfachem drücken. Ist das richtig so?

**Comment by 7h0ma5** [comment]
Das Speichern der Config bewirkt einen Neustart der meisten Komponenten, man kann also eigentlich froh sein, dass die Queue überhaupt erhalten bleibt. Aber ich werde mal sehen, ob sich da was machen lässt.
