### ISSUE TITLE
RasPagerV1 und RasPi3 gehen nicht

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#90]
Laut Stefan M. und DF6EF geht das RasPagerV1 nicht mit einem RasPi3. Vielleicht schauen wir heute abend mal danach?

**Comment by dh3wr** [comment]
Neue Info von Stefan M.:
``Über eine Info, falls Sie eine Lösung finden würde ich mich freuen... werde mich am Wochenende auch nochmal dran setzen, wir hatten schon mal ein ähnliches Problem, dies hatte wohl mit dem timing zu tun, dort lag die Abhilfe in der Veränderung der Prozessorfrequenz 
``

**Comment by DO4DY** [comment]
Ich habe bis jetzt auch das problem das es auf einem pi3 nicht laufen möchte. Software ist da und funktioniert aber es findet keine Aussendung statt.

**Comment by dj7lc** [comment]
Ich habe genau das Problem wie DO4DY mit einem RasPi 1B und Raspbian Stretch. Liegt das möglicherweise am Betriebssystem?

**Comment by DO4DY** [comment]
scheinbar liegt es bei mir an einem leistungs problem es kommen nur -75dbm am ausgang anund diese wurden am frequenzzähler nicht mehr dargestellt am Spectrum Analyzer alerdings nach ein wenig einstellen schon

**Comment by dh3wr** [comment]
@dj7lc Kannst du die Software mal per ``sudo systemctl stop unipager`` stoppen uns als root aus ``/var/lib/unipager`` als Working Dir starten?

Also
````
cd /var/lib/unipager
sudo /usr/bin/unipager
````
Dann kann man vielleicht auf der Konsole noch mehr sehen, was der Grund sein könnte?

**Comment by DO4DY** [comment]
So bei meinem Problem lagen die 3,3 Volt nicht am HF Aussgang an deswegen hatte ich auch keine Leistung

**Comment by dk4pa** [comment]
Hallo, geht es um das Profil RasPagerV1 über UniPager oder eine Hardware Version?
Vy73

**Comment by dh3wr** [comment]
Bei mir geht die Version 1.0.0 mit RaspagerV1 und Raspi 3B

**Comment by dh3wr** [comment]
Hat sich dann erledigt?

**Comment by rtausend** [comment]
Läuft damit wieder, super! Vielen Dank
