### ISSUE TITLE
C9000: error Unable to write data to the serial port 

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPager#96]
Dieses kommt nun bei jeder Sendung, wahrscheinlich bei jedem SerWrite auf die UART. Version 0.7.0.
Aufgetreten bei c9000.db0wa.ampr.org

Der Port ist aber noch da:
````
pi@c9000:/dev $ ls -l /dev/ttyAMA0
crw-rw---- 1 root dialout 204, 64 Sep 28 21:22 /dev/ttyAMA0
````
Soll ich etwas noch testen oder überprüfen, um den Grund besser herausfinden zu können?

**Comment by dh3wr** [comment]
sudo systemctl restart unipager hat keine Änderung gebracht. Nun sudo reboot

**Comment by dh3wr** [comment]
Das hat es behoben...

**Comment by 7h0ma5** [comment]
Kann ich mir nicht erklären. Hattest du versucht den Port mit einem anderen Programm zu öffnen und zu beschreiben als das Problem noch bestand?

**Comment by dh3wr** [comment]
Nein, leider nicht. Aber wäre eine gute Idee gewesen. Ich versuche mal in Nagios-Plugin zu basteln, was die Log-Ausgabe ``error Unable to write data to the serial port`` erkennt und sich dann meldet. Damit wir das in Zukunft schneller mitbekommen. Ebenfalls erhöhe ich den Zeitraum für die ``/var/log/syslog``, damit wir evtl. dort einen Hinweis finden.

**Comment by dh3wr** [comment]
Nagios-Monitoring ist aktiv, wenn auch etwas brute-force:
![grafik](https://user-images.githubusercontent.com/16710361/33614733-7a769bf0-d9d8-11e7-8742-99ad309620dd.png)
Könnte man eine bessere Status-Abfrage implementieren? Der ``Connected`` Status macht ja den Anschein, dass alles ok ist. Dann könnte man das auch einfacher monitoren. Z.B. Anzahl der Fehler in der letzten Stunde.

**Comment by dh3wr** [comment]
Wir tauschen heute den Sender bei DB0WA aus, dann kann man sich die Sache hier auf dem Labortisch nochmal anschauen.

**Comment by dh3wr** [comment]
Grund gefunden: Es hat sich der Bluetooth-Stack (vielleicht durch ein Update) aktiviert. Dadruch war /dev/ttyAMA0 verbogen.
