### ISSUE TITLE
Enhancement: SendMessage - Zusätzliche Optionen

### ISSUE THREAD

**Issue by dk4pa** [rwth-afu/UniPager#98]
Hallo,

mein Vorschlag wäre im Sender Fronted unter Send Message folgende funktionen hinzuzufügen:

IST:
Eingabe für RIC
Eingabe für Message

Zusätzlich:
Auswahl speed (Baudrate): 512,1200,2400 / default 1200
Auswahl mytpe (Typ): Numeric, AlphaNum / default AlphaNum
Auswahl func (Funktionsbit 20,21 aus Adress Code Word) 0-3 / default 3

Hiermit könnten RICs aus Unipager belibig angesteuert werden.

-Ein Zeitruf könnte manuell ausgelöst werden. 
 https://github.com/rwth-afu/UniPager/issues/82

-Die Baudrate kann für den Ruf aus UniPager auf 512bd gesetzt werden. 
 Zumindest um zu testen, welcher Pagertyp worauf reagiert. Hilfreich falls es mal Pagerprofile geben sollte. 
 https://github.com/rwth-afu/UniPager/issues/91

-Mit der Auswahl mytpe: AlphaNum und Auswahl der func: 0-3, könnten die Unteradressen A-D einer
 RIC seperat ausgelöst werden. 

Diese Funktionen dienen erstmal nur aus dem UniPager.
Weiter wäre zu überlegen wie man die Funktionen in Pagerprofile abbilden kann.
Das wäre dann aber vermutlich im Core. 
https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/144

Viele Grüße
Stefan, dk4pa

Anhang: 

Ein kleines Bild als Beispiel.
![sendmessage](https://user-images.githubusercontent.com/25099739/34259450-2e240f7e-e65a-11e7-9213-619abbc8ad07.jpg)

**Comment by dk4pa** [comment]
Hi,

leider funktioniert es noch nicht so wie gedacht.

Speed kann zwar geändert werden, wird auch in UniPager in der Aussendung so angezeigt, jedoch wird das Signal mit 1200bd gesendet.

Wenn MessageTyp = AlphaNum und MessageFunc ist 0 oder 1 werden die Rufe BCD als Numeric kodiert.
bei MessageFunc 2 und 3 werden die Rufe AlphaNum kodiert ( 7-bit ASCII )

Die Funktionen müssten eigentlich so sein, dass überprüft wird, wenn MessageTyp = Alphanum
dann bei MessageFunc 0-3 als 7-bit ASCII Alphanum kodiert wird.

Kann es hiermit zusammenhängen?
https://github.com/rwth-afu/UniPager/blob/d44b2fcae4cad9807fb86b92e5a7b9bed87346f4/src/pocsag/generator.rs#L116

vy73
Stefan, dk4pa

**Comment by 7h0ma5** [comment]
Hallo Stefan,

die Kodierung wurde tatsächlich bisher anhand der Funktionsbits gewählt, was natürlich nur für eine begrenzte Art von Pagern sinnvoll ist. Ich habe das jetzt geändert, dass die Kodierung nur vom MessageType abhängt.

Die Auswahl der Baudrate hat noch keine Wirkung, da es bisher keinen Sender gibt, der andere Baudraten unterstützt. Für den Audio-Sendertyp wäre das aber relativ einfach zu implementieren. Allerdings kommt mit verschiedenen Baudraten noch ein anderes Problem dazu: Nachrichten mit verschiedenen Baudraten können nicht gemischt werden, das ganze Preamble muss dann auch in der anderen Baudrate gesendet werden. Das heißt man benötigt für jede Baudrate eine eigene Warteschlange. Das gibt dann auch wieder neue Probleme bei der Priorisierung (siehe auch https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/122).

73, Thomas DL2IC

**Comment by dk4pa** [comment]
Hallo Thomas,

besten Dank, werde es später direkt testen. 

Habe auch gesehen, dass du die Bezeichnung direkt in Func0-3 als Ausgabe in UniPager geändert hast.
Das wirkt klarer als wenn Nuneric oder Activation steht ;)



Vy73 ,Stefan dk4pa
