### ISSUE TITLE
Bei Update zu 0.7 geht die Konfiguration verloren

### ISSUE THREAD

**Issue by dj7lc** [rwth-afu/UniPager#99]
Bei Update zu 0.7 via "apt upgrade" geht die Konfiguration verloren.

**Comment by dj7lc** [comment]
Und in der Infobox sind jetzt interessante Bitmuster:
` Connected to UniPager.
warn Connecting to next fallback server...
error No callsign configured.
error Connection failed.
error No callsign configured.
error Connection failed.
warn Connecting to next fallback server...
error No callsign configured.
error Connection failed.
error No callsign configured.
error Connection failed.
warn Connecting to next fallback server...
error No callsign configured.
error Connection failed.
error No callsign configured.
error Connection failed.
warn Connecting to next fallback server...
error No callsign configured.
error Connection failed.
error No callsign configured.
error Connection failed.
warn Connecting to next fallback server...
error No callsign configured.
error Connection failed.
info Config updated. Initiating restart.
info Waiting for the connection to terminate...
info Waiting for the scheduler to terminate...
info Scheduler stopped.
warn Using dummy transmitter
info Scheduler started.
info Connection to dapnet.db0vvs.ampr.org:43434...
info Connection established.
info Set TimeSlots { 3B }
info Received Message { id: 0, mtype: Numeric, speed: Baud(1200), addr: 2504, func: Numeric, data: "112600 141217" }
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 01111100110100100001010111011000
info 00000000001001110010010100110111
info 11000100001000110000010010110101
info 10000001100110011100010110101111
info 10010100001001000111010000100000
info 10011001100110011001111101000111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info Received Message { id: 1, mtype: Numeric, speed: Baud(1200), addr: 2504, func: Numeric, data: "112700 141217" }
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 01111100110100100001010111011000
info 00000000001001110010010100110111
info 11000100001001110000000110001110
info 10000001100110011100010110101111
info 10010100001001000111010000100000
info 10011001100110011001111101000111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info Received Message { id: 2, mtype: Numeric, speed: Baud(1200), addr: 2504, func: Numeric, data: "112800 141217" }
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 01111100110100100001010111011000
info 00000000001001110010010100110111
info 11000100001000001000010110101110
info 10000001100110011100010110101111
info 10010100001001000111010000100000
info 10011001100110011001111101000111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info Received Message { id: 3, mtype: Numeric, speed: Baud(1200), addr: 2504, func: Numeric, data: "112900 141217" }
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 10101010101010101010101010101010
info 01111100110100100001010111011000
info 00000000001001110010010100110111
info 11000100001001001000000010010101
info 10000001100110011100010110101111
info 10010100001001000111010000100000
info 10011001100110011001111101000111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111
info 01111010100010011100000110010111 `

**Comment by 7h0ma5** [comment]
Handelt es sich um einen C9000? Da gab es mehrere Änderungen in der Konfiguration. Wenn es nur da auftritt kann ich vielleicht noch etwas ändern, damit das Update problemlos läuft. Die Bitmuster sind normal, wenn der Dummy-Transmitter gewählt ist, die Rohdaten werden dann zu Debugging-Zwecken ausgegeben.

**Comment by dj7lc** [comment]
Ah ja, dann ist das Rätsel schon mal gelöst. Der Sender ist ein Raspager V1.

**Comment by 7h0ma5** [comment]
Das Problem ist gefunden und behoben. Version 0.7.1 wird gerade von Jenkins kompiliert und müsste in etwa 20 Minuten im Repository verfügbar sein. Hier findet man den aktuellen Status: http://ci.db0sda.ampr.org:8080/job/unipager-binaries/

**Comment by dj7lc** [comment]
Super! Gleich mal installieren...
